/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import java.io.File;
import javax.swing.JOptionPane;
import Modelo.Personaje;
import java.util.ArrayList;
/**
 *
 * @author puesto1
 */
public class Creacion_Personaje extends javax.swing.JFrame {
    int est = 150;
    int hab = 5;
    int cont30 = 0;
    int cont20 = 0;
    private boolean valido = true;
    private ArrayList<String> habiliades = new ArrayList();
    int cort = 0;
    
    
    
    /** Creates new form Creacion_Personaje */
    public Creacion_Personaje() {
        
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldApe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldProf = new javax.swing.JTextField();
        jPanelEst = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButtonFue = new javax.swing.JButton();
        jButtonCon = new javax.swing.JButton();
        jButtonTam = new javax.swing.JButton();
        jButtonDes = new javax.swing.JButton();
        jButtonInt = new javax.swing.JButton();
        jButtonEdu = new javax.swing.JButton();
        jButtonAddFue = new javax.swing.JButton();
        jButtonAddCon = new javax.swing.JButton();
        jButtonAddTam = new javax.swing.JButton();
        jButtonAddInt = new javax.swing.JButton();
        jButtonAddEdu = new javax.swing.JButton();
        jButtonAddDes = new javax.swing.JButton();
        jLabelFue = new javax.swing.JLabel();
        jLabelCon = new javax.swing.JLabel();
        jLabelTam = new javax.swing.JLabel();
        jLabelInt = new javax.swing.JLabel();
        jLabelEdu = new javax.swing.JLabel();
        jLabelDes = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButtonAnt = new javax.swing.JRadioButton();
        jRadioButtonBio = new javax.swing.JRadioButton();
        jRadioButtonBuscLib = new javax.swing.JRadioButton();
        jRadioButtonCerr = new javax.swing.JRadioButton();
        jRadioButtonCienOcu = new javax.swing.JRadioButton();
        jRadioButtonDesc = new javax.swing.JRadioButton();
        jRadioButtonDisc = new javax.swing.JRadioButton();
        jRadioButtonEsc = new javax.swing.JRadioButton();
        jRadioButtonEsq = new javax.swing.JRadioButton();
        jRadioButtonFarm = new javax.swing.JRadioButton();
        jRadioButtonHist = new javax.swing.JRadioButton();
        jRadioButtonMec = new javax.swing.JRadioButton();
        jRadioButtonMed = new javax.swing.JRadioButton();
        jRadioButtonOcu = new javax.swing.JRadioButton();
        jRadioButtonLat = new javax.swing.JRadioButton();
        jRadioButtonFran = new javax.swing.JRadioButton();
        jRadioButtonRus = new javax.swing.JRadioButton();
        jRadioButtonPers = new javax.swing.JRadioButton();
        jRadioButtonPsi = new javax.swing.JRadioButton();
        jRadioButtonSegRas = new javax.swing.JRadioButton();
        jRadioButtonArmFug = new javax.swing.JRadioButton();
        jButtonDesc = new javax.swing.JButton();
        jButtonBio = new javax.swing.JButton();
        jButtonBuscLib = new javax.swing.JButton();
        jButtonCerr = new javax.swing.JButton();
        jButtonCienOcu = new javax.swing.JButton();
        jButtonAnt = new javax.swing.JButton();
        jButtonDis = new javax.swing.JButton();
        jButtonMed = new javax.swing.JButton();
        jButtonEsq = new javax.swing.JButton();
        jButtonFar = new javax.swing.JButton();
        jButtonHis = new javax.swing.JButton();
        jButtonMec = new javax.swing.JButton();
        jButtonEsc = new javax.swing.JButton();
        jButtonOcu = new javax.swing.JButton();
        jButtonSegRas = new javax.swing.JButton();
        jButtonFra = new javax.swing.JButton();
        jButtonRus = new javax.swing.JButton();
        jButtonPer = new javax.swing.JButton();
        jButtonPsi = new javax.swing.JButton();
        jButtonLat = new javax.swing.JButton();
        jButtonArmFug = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jButtonAcep = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabelHab = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombre:");

        jTextFieldNom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Apellido:");

        jTextFieldApe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Profesion:");

        jTextFieldProf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProfActionPerformed(evt);
            }
        });

        jPanelEst.setBorder(javax.swing.BorderFactory.createTitledBorder("Estadisticas"));

        jLabel6.setText("FUE:");

        jLabel3.setText("CON:");

        jLabel7.setText("TAM:");

        jLabel8.setText("DES:");

        jLabel10.setText("INT:");

        jLabel11.setText("EDU:");

        jButtonFue.setText("?");
        jButtonFue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFueActionPerformed(evt);
            }
        });

        jButtonCon.setText("?");
        jButtonCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConActionPerformed(evt);
            }
        });

        jButtonTam.setText("?");
        jButtonTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTamActionPerformed(evt);
            }
        });

        jButtonDes.setText("?");
        jButtonDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesActionPerformed(evt);
            }
        });

        jButtonInt.setText("?");
        jButtonInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIntActionPerformed(evt);
            }
        });

        jButtonEdu.setText("?");
        jButtonEdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEduActionPerformed(evt);
            }
        });

        jButtonAddFue.setText("40");
        jButtonAddFue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddFueActionPerformed(evt);
            }
        });

        jButtonAddCon.setText("40");
        jButtonAddCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddConActionPerformed(evt);
            }
        });

        jButtonAddTam.setText("40");
        jButtonAddTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTamActionPerformed(evt);
            }
        });

        jButtonAddInt.setText("40");
        jButtonAddInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddIntActionPerformed(evt);
            }
        });

        jButtonAddEdu.setText("40");
        jButtonAddEdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddEduActionPerformed(evt);
            }
        });

        jButtonAddDes.setText("40");
        jButtonAddDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddDesActionPerformed(evt);
            }
        });

        jLabelFue.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelFue.setText("50");

        jLabelCon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCon.setText("50");

        jLabelTam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTam.setText("50");

        jLabelInt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelInt.setText("50");

        jLabelEdu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelEdu.setText("50");

        jLabelDes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelDes.setText("50");

        javax.swing.GroupLayout jPanelEstLayout = new javax.swing.GroupLayout(jPanelEst);
        jPanelEst.setLayout(jPanelEstLayout);
        jPanelEstLayout.setHorizontalGroup(
            jPanelEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEstLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelTam))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelEstLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                            .addComponent(jLabelCon))
                        .addGroup(jPanelEstLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelFue))))
                .addGap(18, 18, 18)
                .addGroup(jPanelEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAddCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAddTam)
                    .addComponent(jButtonAddFue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanelEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFue)
                    .addComponent(jButtonTam)
                    .addComponent(jButtonCon))
                .addGap(28, 28, 28)
                .addGroup(jPanelEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanelEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInt)
                    .addComponent(jLabelEdu)
                    .addComponent(jLabelDes))
                .addGap(18, 18, 18)
                .addGroup(jPanelEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelEstLayout.createSequentialGroup()
                        .addComponent(jButtonAddDes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDes))
                    .addGroup(jPanelEstLayout.createSequentialGroup()
                        .addComponent(jButtonAddInt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonInt))
                    .addGroup(jPanelEstLayout.createSequentialGroup()
                        .addComponent(jButtonAddEdu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEdu)))
                .addGap(48, 48, 48))
        );
        jPanelEstLayout.setVerticalGroup(
            jPanelEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanelEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEstLayout.createSequentialGroup()
                        .addGroup(jPanelEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonFue)
                            .addGroup(jPanelEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabelInt)
                                .addComponent(jButtonAddInt)
                                .addComponent(jButtonInt)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonCon)
                                .addComponent(jLabel11)
                                .addComponent(jLabelEdu))
                            .addComponent(jButtonEdu)
                            .addComponent(jButtonAddEdu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonTam)
                            .addComponent(jButtonAddTam)
                            .addComponent(jLabel8)
                            .addComponent(jButtonAddDes)
                            .addComponent(jButtonDes)
                            .addComponent(jLabelDes)))
                    .addGroup(jPanelEstLayout.createSequentialGroup()
                        .addGroup(jPanelEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEstLayout.createSequentialGroup()
                                .addComponent(jButtonAddFue)
                                .addGap(18, 18, 18)
                                .addGroup(jPanelEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonAddCon)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabelCon)))
                            .addGroup(jPanelEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabelFue)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTam)
                            .addComponent(jLabel7))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Habiliadades"));

        jRadioButtonAnt.setText("Antropologia");
        jRadioButtonAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAntActionPerformed(evt);
            }
        });

        jRadioButtonBio.setText("Biologia");
        jRadioButtonBio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBioActionPerformed(evt);
            }
        });

        jRadioButtonBuscLib.setText("Buscar Libros");
        jRadioButtonBuscLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBuscLibActionPerformed(evt);
            }
        });

        jRadioButtonCerr.setText("Cerrajeria");
        jRadioButtonCerr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCerrActionPerformed(evt);
            }
        });

        jRadioButtonCienOcu.setText("Ciencias Ocultas");
        jRadioButtonCienOcu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCienOcuActionPerformed(evt);
            }
        });

        jRadioButtonDesc.setText("Descubrir");
        jRadioButtonDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDescActionPerformed(evt);
            }
        });

        jRadioButtonDisc.setText("Discreción");
        jRadioButtonDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDiscActionPerformed(evt);
            }
        });

        jRadioButtonEsc.setText("Escuchar");
        jRadioButtonEsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEscActionPerformed(evt);
            }
        });

        jRadioButtonEsq.setText("Esquivar");
        jRadioButtonEsq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEsqActionPerformed(evt);
            }
        });

        jRadioButtonFarm.setText("Farmacologia");
        jRadioButtonFarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFarmActionPerformed(evt);
            }
        });

        jRadioButtonHist.setText("Historia");
        jRadioButtonHist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHistActionPerformed(evt);
            }
        });

        jRadioButtonMec.setText("Mecanica");
        jRadioButtonMec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMecActionPerformed(evt);
            }
        });

        jRadioButtonMed.setText("Medicina");
        jRadioButtonMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMedActionPerformed(evt);
            }
        });

        jRadioButtonOcu.setText("Ocultar");
        jRadioButtonOcu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOcuActionPerformed(evt);
            }
        });

        jRadioButtonLat.setText("Latín");
        jRadioButtonLat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLatActionPerformed(evt);
            }
        });

        jRadioButtonFran.setText("Frances");
        jRadioButtonFran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFranActionPerformed(evt);
            }
        });

        jRadioButtonRus.setText("Ruso");
        jRadioButtonRus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRusActionPerformed(evt);
            }
        });

        jRadioButtonPers.setText("Persuasión");
        jRadioButtonPers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPersActionPerformed(evt);
            }
        });

        jRadioButtonPsi.setText("Psicologia");
        jRadioButtonPsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPsiActionPerformed(evt);
            }
        });

        jRadioButtonSegRas.setText("Segir Rastros");
        jRadioButtonSegRas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSegRasActionPerformed(evt);
            }
        });

        jRadioButtonArmFug.setText("Armas de Fuego");
        jRadioButtonArmFug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonArmFugActionPerformed(evt);
            }
        });

        jButtonDesc.setText("?");
        jButtonDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDescActionPerformed(evt);
            }
        });

        jButtonBio.setText("?");
        jButtonBio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBioActionPerformed(evt);
            }
        });

        jButtonBuscLib.setText("?");
        jButtonBuscLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscLibActionPerformed(evt);
            }
        });

        jButtonCerr.setText("?");
        jButtonCerr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrActionPerformed(evt);
            }
        });

        jButtonCienOcu.setText("?");
        jButtonCienOcu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCienOcuActionPerformed(evt);
            }
        });

        jButtonAnt.setText("?");
        jButtonAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAntActionPerformed(evt);
            }
        });

        jButtonDis.setText("?");
        jButtonDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDisActionPerformed(evt);
            }
        });

        jButtonMed.setText("?");
        jButtonMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedActionPerformed(evt);
            }
        });

        jButtonEsq.setText("?");
        jButtonEsq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEsqActionPerformed(evt);
            }
        });

        jButtonFar.setText("?");
        jButtonFar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFarActionPerformed(evt);
            }
        });

        jButtonHis.setText("?");
        jButtonHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHisActionPerformed(evt);
            }
        });

        jButtonMec.setText("?");
        jButtonMec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMecActionPerformed(evt);
            }
        });

        jButtonEsc.setText("?");
        jButtonEsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEscActionPerformed(evt);
            }
        });

        jButtonOcu.setText("?");
        jButtonOcu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOcuActionPerformed(evt);
            }
        });

        jButtonSegRas.setText("?");
        jButtonSegRas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSegRasActionPerformed(evt);
            }
        });

        jButtonFra.setText("?");
        jButtonFra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFraActionPerformed(evt);
            }
        });

        jButtonRus.setText("?");
        jButtonRus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRusActionPerformed(evt);
            }
        });

        jButtonPer.setText("?");
        jButtonPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPerActionPerformed(evt);
            }
        });

        jButtonPsi.setText("?");
        jButtonPsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPsiActionPerformed(evt);
            }
        });

        jButtonLat.setText("?");
        jButtonLat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLatActionPerformed(evt);
            }
        });

        jButtonArmFug.setText("?");
        jButtonArmFug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArmFugActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonAnt)
                            .addComponent(jRadioButtonBio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBio))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jRadioButtonCerr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCerr))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jRadioButtonBuscLib)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBuscLib))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jRadioButtonCienOcu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCienOcu))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonDesc)
                            .addComponent(jRadioButtonDisc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAnt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonDesc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonDis, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonEsc)
                    .addComponent(jRadioButtonOcu)
                    .addComponent(jRadioButtonMed)
                    .addComponent(jRadioButtonMec)
                    .addComponent(jRadioButtonHist)
                    .addComponent(jRadioButtonFarm)
                    .addComponent(jRadioButtonEsq))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEsq)
                    .addComponent(jButtonHis)
                    .addComponent(jButtonFar)
                    .addComponent(jButtonMec)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonEsc, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonMed, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonOcu, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonLat)
                    .addComponent(jRadioButtonArmFug)
                    .addComponent(jRadioButtonSegRas)
                    .addComponent(jRadioButtonPsi)
                    .addComponent(jRadioButtonPers)
                    .addComponent(jRadioButtonRus)
                    .addComponent(jRadioButtonFran))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFra)
                    .addComponent(jButtonPer)
                    .addComponent(jButtonRus)
                    .addComponent(jButtonPsi)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonLat, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonSegRas, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonArmFug, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jButtonFra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonRus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonPer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonPsi))
                            .addComponent(jButtonLat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSegRas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonArmFug))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jButtonEsq)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonFar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonHis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonMec))
                            .addComponent(jButtonEsc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonMed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOcu))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButtonAnt)
                                    .addComponent(jRadioButtonEsc)
                                    .addComponent(jRadioButtonLat))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButtonBio)
                                    .addComponent(jRadioButtonEsq)
                                    .addComponent(jRadioButtonFran)
                                    .addComponent(jButtonBio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButtonBuscLib)
                                    .addComponent(jRadioButtonFarm)
                                    .addComponent(jRadioButtonRus)
                                    .addComponent(jButtonBuscLib))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButtonCerr)
                                    .addComponent(jRadioButtonHist)
                                    .addComponent(jRadioButtonPers)
                                    .addComponent(jButtonCerr))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButtonCienOcu)
                                    .addComponent(jRadioButtonMec)
                                    .addComponent(jRadioButtonPsi)
                                    .addComponent(jButtonCienOcu)))
                            .addComponent(jButtonAnt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonDesc)
                            .addComponent(jRadioButtonMed)
                            .addComponent(jRadioButtonSegRas)
                            .addComponent(jButtonDesc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonDisc)
                            .addComponent(jRadioButtonOcu)
                            .addComponent(jRadioButtonArmFug)
                            .addComponent(jButtonDis))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Sexo:");

        jComboBoxSexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));

        jButtonAcep.setText("Aceptar");
        jButtonAcep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcepActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Puntos de Habilidad:");

        jLabelHab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelHab.setText("5");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldApe, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldProf, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonAcep, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelHab)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelEst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jButtonAcep, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabelHab, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProfActionPerformed

    private void jButtonFueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFueActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Fuerza: ayuda en las tiradas que tengan que ver con la fuerza");
    }//GEN-LAST:event_jButtonFueActionPerformed

    private void jButtonConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Constitucion: ayuda en las tiradas que tengan que ver con la resistencia fisica y en tu vida maxima");
    }//GEN-LAST:event_jButtonConActionPerformed

    private void jButtonTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTamActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Tamaño: mejora tu vid amaxima y bonus de daño");
    }//GEN-LAST:event_jButtonTamActionPerformed

    private void jButtonDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Agilidad: ayuda en las tiradas que tengan que con la agilidad de reflejos");
    }//GEN-LAST:event_jButtonDesActionPerformed

    private void jButtonIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIntActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Inteligencia: ayuda en las tiradas que tengan con que cosas sabe tu persoanje");
    }//GEN-LAST:event_jButtonIntActionPerformed

    private void jButtonEduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEduActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Educacion: ayuda en las tiradas que tengan que ver con los estudios del personaje");
    }//GEN-LAST:event_jButtonEduActionPerformed

    private void jButtonAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAntActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Ayuda a buscar informacion sobre un cadaver");
    }//GEN-LAST:event_jButtonAntActionPerformed

    private void jButtonBioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBioActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Ayuda a buscar informacion sobre animales");
    }//GEN-LAST:event_jButtonBioActionPerformed

    private void jButtonBuscLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscLibActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Ayuda en las tiradeas en las que se busquen libros");
    }//GEN-LAST:event_jButtonBuscLibActionPerformed

    private void jButtonCerrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Ayuda a abrir cerraduras");
    }//GEN-LAST:event_jButtonCerrActionPerformed

    private void jButtonCienOcuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCienOcuActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Ayuda a buscar informacion sobre lo oculto");
    }//GEN-LAST:event_jButtonCienOcuActionPerformed

    private void jButtonDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDescActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Ayuda a buscar objetos ocultos");
    }//GEN-LAST:event_jButtonDescActionPerformed

    private void jButtonDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Ayuda a la hora de pasar desapercibido");
    }//GEN-LAST:event_jButtonDisActionPerformed

    private void jButtonEscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEscActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Ayuda a escuchar conversaciones ajenas");
    }//GEN-LAST:event_jButtonEscActionPerformed

    private void jButtonEsqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEsqActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Ayuda a esquivar golpes");
    }//GEN-LAST:event_jButtonEsqActionPerformed

    private void jButtonFarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Ayuda a buscar informacion sobre farmacos");
    }//GEN-LAST:event_jButtonFarActionPerformed

    private void jButtonHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHisActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Ayuda a buscar informacion sobre datos historicos");
    }//GEN-LAST:event_jButtonHisActionPerformed

    private void jButtonMecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMecActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Ayuda a areglar maquinaris");
    }//GEN-LAST:event_jButtonMecActionPerformed

    private void jButtonMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Ayuda a tratar heridas");
    }//GEN-LAST:event_jButtonMedActionPerformed

    private void jButtonOcuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOcuActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Ayuda a esconder objetos");
    }//GEN-LAST:event_jButtonOcuActionPerformed

    private void jButtonLatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLatActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Sabes latin");
    }//GEN-LAST:event_jButtonLatActionPerformed

    private void jButtonFraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFraActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Sabes frances");
    }//GEN-LAST:event_jButtonFraActionPerformed

    private void jButtonRusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRusActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"sabes ruso");
    }//GEN-LAST:event_jButtonRusActionPerformed

    private void jButtonPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPerActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Ayuda a convencer a otras personas");
    }//GEN-LAST:event_jButtonPerActionPerformed

    private void jButtonPsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPsiActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Ayuda a saber que piensa una persona");
    }//GEN-LAST:event_jButtonPsiActionPerformed

    private void jButtonSegRasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSegRasActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Ayuda a seguir pistas");
    }//GEN-LAST:event_jButtonSegRasActionPerformed

    private void jButtonArmFugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArmFugActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Ayuda a disparar mejor");
    }//GEN-LAST:event_jButtonArmFugActionPerformed

    private void jButtonAcepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcepActionPerformed
        // TODO add your handling code here:
        
        String nom = jTextFieldNom.getText();
        String ape = jTextFieldApe.getText();
        String pro = jTextFieldProf.getText();
        
        if (hab == 0 && cort == 1 ){
            
          Personaje p = new Personaje();
        
        p.setNombre(jTextFieldNom.getText());
        p.setApellidos(jTextFieldApe.getText());
        p.setProfesion(jTextFieldProf.getText());
        p.setSexo((String) jComboBoxSexo.getSelectedItem());
         
        p.setFuerza(Integer.parseInt(jLabelFue.getText()));
        p.setConstitucion(Integer.parseInt(jLabelCon.getText()));
        p.setTamano(Integer.parseInt(jLabelTam.getText()));
        p.setDestreza(Integer.parseInt(jLabelDes.getText()));
        p.setInteligencia(Integer.parseInt(jLabelInt.getText()));
        p.setEducacion(Integer.parseInt(jLabelEdu.getText()));
        
        p.setHabiliades(habiliades);
        
        new Principal (p, habiliades).setVisible(true);
        //new Principal ().setVisible(true);
        this.dispose();   
            
        }else {
            
           JOptionPane.showMessageDialog(null,"Completa la ficha"); 
            
        }
        
            
    }//GEN-LAST:event_jButtonAcepActionPerformed

    private void jRadioButtonAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAntActionPerformed
        // TODO add your handling code here:
        
        if (jRadioButtonAnt.isSelected() && hab > 0){
            hab = hab-1;
            habiliades.add("Antropologia");
            jLabelHab.setText(Integer.toString(hab));
            
        }else if(!jRadioButtonAnt.isSelected()){
            
            hab = hab+1;
            habiliades.remove("Antropologia");
            jLabelHab.setText(Integer.toString(hab));
            
        }else {
            
            JOptionPane.showMessageDialog(null,"Ya has gastado todos los puntos de habilidad");
            
        }
        
    }//GEN-LAST:event_jRadioButtonAntActionPerformed

    private void jRadioButtonBioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBioActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonBio.isSelected() && hab > 0){
            hab = hab-1;
            habiliades.add("Biologia");
            jLabelHab.setText(Integer.toString(hab));
            
        }else if(!jRadioButtonBio.isSelected()){
            
            hab = hab+1;
            habiliades.remove("Biologia");
            jLabelHab.setText(Integer.toString(hab));
            
        }else {
            
            JOptionPane.showMessageDialog(null,"Ya has gastado todos los puntos de habilidad");
            jRadioButtonBio.setSelected(false);
        }
        
    }//GEN-LAST:event_jRadioButtonBioActionPerformed

    private void jRadioButtonBuscLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBuscLibActionPerformed
        // TODO add your handling code here:
        
        if (jRadioButtonBuscLib.isSelected() && hab > 0){
            hab = hab-1;
            habiliades.add("Buscar Libros");
            jLabelHab.setText(Integer.toString(hab));
            
        }else if(!jRadioButtonBuscLib.isSelected()){
            
            hab = hab+1;
            habiliades.remove("Buscar Libros");
            jLabelHab.setText(Integer.toString(hab));
            
        }else {
            
            JOptionPane.showMessageDialog(null,"Ya has gastado todos los puntos de habilidad");
            jRadioButtonBuscLib.setSelected(false);
        }
        
    }//GEN-LAST:event_jRadioButtonBuscLibActionPerformed

    private void jRadioButtonCerrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCerrActionPerformed
        // TODO add your handling code here:
        
        if (jRadioButtonCerr.isSelected() && hab > 0){
            hab = hab-1;
            habiliades.add("Cerrajeria");
            jLabelHab.setText(Integer.toString(hab));
            
        }else if(!jRadioButtonCerr.isSelected()){
            
            hab = hab+1;
            habiliades.remove("Cerrajeria");
            jLabelHab.setText(Integer.toString(hab));
            
        }else {
            
            JOptionPane.showMessageDialog(null,"Ya has gastado todos los puntos de habilidad");
            jRadioButtonCerr.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonCerrActionPerformed

    private void jRadioButtonCienOcuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCienOcuActionPerformed
        // TODO add your handling code here:
        
        if (jRadioButtonCienOcu.isSelected() && hab > 0){
            hab = hab-1;
            habiliades.add("Ciencias Ocultas");
            jLabelHab.setText(Integer.toString(hab));
            
        }else if(!jRadioButtonCienOcu.isSelected()){
            
            hab = hab+1;
            habiliades.remove("Ciencias Ocultas");
            jLabelHab.setText(Integer.toString(hab));
            
        }else {
            
            JOptionPane.showMessageDialog(null,"Ya has gastado todos los puntos de habilidad");
            jRadioButtonCienOcu.setSelected(false);
        }
        
    }//GEN-LAST:event_jRadioButtonCienOcuActionPerformed

    private void jRadioButtonDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDescActionPerformed
        // TODO add your handling code here:
        
        if (jRadioButtonDesc.isSelected() && hab > 0){
            hab = hab-1;
            habiliades.add("Descubrir");
            jLabelHab.setText(Integer.toString(hab));
            
        }else if(!jRadioButtonDesc.isSelected()){
            
            hab = hab+1;
            habiliades.remove("Descubrir");
            jLabelHab.setText(Integer.toString(hab));
            
        }else {
            
            JOptionPane.showMessageDialog(null,"Ya has gastado todos los puntos de habilidad");
            jRadioButtonDesc.setSelected(false);
        }
        
    }//GEN-LAST:event_jRadioButtonDescActionPerformed

    private void jRadioButtonDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDiscActionPerformed
        // TODO add your handling code here:
        
        if (jRadioButtonDisc.isSelected() && hab > 0){
            hab = hab-1;
            habiliades.add("Discrecion");
            jLabelHab.setText(Integer.toString(hab));
            
        }else if(!jRadioButtonDisc.isSelected()){
            
            hab = hab+1;
            habiliades.remove("Discrecion");
            jLabelHab.setText(Integer.toString(hab));
            
        }else {
            
            JOptionPane.showMessageDialog(null,"Ya has gastado todos los puntos de habilidad");
            jRadioButtonDisc.setSelected(false);
        }
        
    }//GEN-LAST:event_jRadioButtonDiscActionPerformed

    private void jRadioButtonEscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEscActionPerformed
        // TODO add your handling code here:
        
        if (jRadioButtonEsc.isSelected() && hab > 0){
            hab = hab-1;
            habiliades.add("Escuchar");
            jLabelHab.setText(Integer.toString(hab));
            
        }else if(!jRadioButtonEsc.isSelected()){
            
            hab = hab+1;
            habiliades.remove("Escucahr");
            jLabelHab.setText(Integer.toString(hab));
            
        }else {
            
            JOptionPane.showMessageDialog(null,"Ya has gastado todos los puntos de habilidad");
            jRadioButtonEsc.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonEscActionPerformed

    private void jRadioButtonEsqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEsqActionPerformed
        // TODO add your handling code here:
        
        if (jRadioButtonEsq.isSelected() && hab > 0){
            hab = hab-1;
            habiliades.add("Esquivar");
            jLabelHab.setText(Integer.toString(hab));
            
        }else if(!jRadioButtonEsq.isSelected()){
            
            hab = hab+1;
            habiliades.remove("Esquivar");
            jLabelHab.setText(Integer.toString(hab));
            
        }else {
            
            JOptionPane.showMessageDialog(null,"Ya has gastado todos los puntos de habilidad");
            jRadioButtonEsq.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonEsqActionPerformed

    private void jRadioButtonFarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFarmActionPerformed
        // TODO add your handling code here:
        
        if (jRadioButtonFarm.isSelected() && hab > 0){
            hab = hab-1;
            habiliades.add("Farmacologia");
            jLabelHab.setText(Integer.toString(hab));
            
        }else if(!jRadioButtonFarm.isSelected()){
            
            hab = hab+1;
            habiliades.remove("Framacologia");
            jLabelHab.setText(Integer.toString(hab));
            
        }else {
            
            JOptionPane.showMessageDialog(null,"Ya has gastado todos los puntos de habilidad");
            jRadioButtonFarm.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonFarmActionPerformed

    private void jRadioButtonHistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHistActionPerformed
        // TODO add your handling code here:
        
        if (jRadioButtonHist.isSelected() && hab > 0){
            hab = hab-1;
            habiliades.add("Historia");
            jLabelHab.setText(Integer.toString(hab));
            
        }else if(!jRadioButtonHist.isSelected()){
            
            hab = hab+1;
            habiliades.remove("Historia");
            jLabelHab.setText(Integer.toString(hab));
            
        }else {
            
            JOptionPane.showMessageDialog(null,"Ya has gastado todos los puntos de habilidad");
            jRadioButtonHist.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonHistActionPerformed

    private void jRadioButtonMecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMecActionPerformed
        // TODO add your handling code here:
        
        if (jRadioButtonMec.isSelected() && hab > 0){
            hab = hab-1;
            habiliades.add("Mecanica");
            jLabelHab.setText(Integer.toString(hab));
            
        }else if(!jRadioButtonMec.isSelected()){
            
            hab = hab+1;
            habiliades.remove("Mecanica");
            jLabelHab.setText(Integer.toString(hab));
            
        }else {
            
            JOptionPane.showMessageDialog(null,"Ya has gastado todos los puntos de habilidad");
            jRadioButtonMec.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonMecActionPerformed

    private void jRadioButtonMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMedActionPerformed
        // TODO add your handling code here:
        
        if (jRadioButtonMed.isSelected() && hab > 0){
            hab = hab-1;
            habiliades.add("Medicina");
            jLabelHab.setText(Integer.toString(hab));
            
        }else if(!jRadioButtonMed.isSelected()){
            
            hab = hab+1;
            habiliades.remove("Medicina");
            jLabelHab.setText(Integer.toString(hab));
            
        }else {
            
            JOptionPane.showMessageDialog(null,"Ya has gastado todos los puntos de habilidad");
            jRadioButtonMed.setSelected(false);
        }
        
    }//GEN-LAST:event_jRadioButtonMedActionPerformed

    private void jRadioButtonOcuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOcuActionPerformed
        // TODO add your handling code here:
        
        if (jRadioButtonOcu.isSelected() && hab > 0){
            hab = hab-1;
            habiliades.add("Ocultar");
            jLabelHab.setText(Integer.toString(hab));
            
        }else if(!jRadioButtonOcu.isSelected()){
            
            hab = hab+1;
            habiliades.remove("Ocultar");
            jLabelHab.setText(Integer.toString(hab));
            
        }else {
            
            JOptionPane.showMessageDialog(null,"Ya has gastado todos los puntos de habilidad");
            jRadioButtonOcu.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonOcuActionPerformed

    private void jRadioButtonLatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLatActionPerformed
        // TODO add your handling code here:
        
        if (jRadioButtonLat.isSelected() && hab > 0){
            hab = hab-1;
            habiliades.add("Latin");
            jLabelHab.setText(Integer.toString(hab));
            
        }else if(!jRadioButtonLat.isSelected()){
            
            hab = hab+1;
            habiliades.remove("Latin");
            jLabelHab.setText(Integer.toString(hab));
            
        }else {
            
            JOptionPane.showMessageDialog(null,"Ya has gastado todos los puntos de habilidad");
            jRadioButtonLat.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonLatActionPerformed

    private void jRadioButtonFranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFranActionPerformed
        // TODO add your handling code here:
        
        if (jRadioButtonFran.isSelected() && hab > 0){
            hab = hab-1;
            habiliades.add("Frances");
            jLabelHab.setText(Integer.toString(hab));
            
        }else if(!jRadioButtonFran.isSelected()){
            
            hab = hab+1;
            habiliades.remove("Frances");
            jLabelHab.setText(Integer.toString(hab));
            
        }else {
            
            JOptionPane.showMessageDialog(null,"Ya has gastado todos los puntos de habilidad");
            jRadioButtonFran.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonFranActionPerformed

    private void jRadioButtonRusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRusActionPerformed
        // TODO add your handling code here:
        
        if (jRadioButtonRus.isSelected() && hab > 0){
            hab = hab-1;
            habiliades.add("Ruso");
            jLabelHab.setText(Integer.toString(hab));
            
        }else if(!jRadioButtonRus.isSelected()){
            
            hab = hab+1;
            habiliades.remove("Ruso");
            jLabelHab.setText(Integer.toString(hab));
            
        }else {
            
            JOptionPane.showMessageDialog(null,"Ya has gastado todos los puntos de habilidad");
            jRadioButtonRus.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonRusActionPerformed

    private void jRadioButtonPersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPersActionPerformed
        // TODO add your handling code here:
        
        if (jRadioButtonPers.isSelected() && hab > 0){
            hab = hab-1;
            habiliades.add("Persuasion");
            jLabelHab.setText(Integer.toString(hab));
            
        }else if(!jRadioButtonPers.isSelected()){
            
            hab = hab+1;
            habiliades.remove("Persuasion");
            jLabelHab.setText(Integer.toString(hab));
            
        }else {
            
            JOptionPane.showMessageDialog(null,"Ya has gastado todos los puntos de habilidad");
            jRadioButtonPers.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonPersActionPerformed

    private void jRadioButtonPsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPsiActionPerformed
        // TODO add your handling code here:
        
        if (jRadioButtonPsi.isSelected() && hab > 0){
            hab = hab-1;
            habiliades.add("Psicologia");
            jLabelHab.setText(Integer.toString(hab));
            
        }else if(!jRadioButtonPsi.isSelected()){
            
            hab = hab+1;
            habiliades.remove("Psicologia");
            jLabelHab.setText(Integer.toString(hab));
            
        }else {
            
            JOptionPane.showMessageDialog(null,"Ya has gastado todos los puntos de habilidad");
            jRadioButtonPsi.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonPsiActionPerformed

    private void jRadioButtonSegRasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSegRasActionPerformed
        // TODO add your handling code here:
        
        if (jRadioButtonSegRas.isSelected() && hab > 0){
            hab = hab-1;
            habiliades.add("Seguir Rastros");
            jLabelHab.setText(Integer.toString(hab));
            
        }else if(!jRadioButtonSegRas.isSelected()){
            
            hab = hab+1;
            habiliades.remove("Seguir Rastros");
            jLabelHab.setText(Integer.toString(hab));
            
        }else {
            
            JOptionPane.showMessageDialog(null,"Ya has gastado todos los puntos de habilidad");
            jRadioButtonSegRas.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonSegRasActionPerformed

    private void jRadioButtonArmFugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonArmFugActionPerformed
        // TODO add your handling code here:
        
        if (jRadioButtonArmFug.isSelected() && hab > 0){
            hab = hab-1;
            habiliades.add("Armas de Fuego");
            jLabelHab.setText(Integer.toString(hab));
            
        }else if(!jRadioButtonAnt.isSelected()){
            
            hab = hab+1;
            habiliades.remove("Armas de Fuego");
            jLabelHab.setText(Integer.toString(hab));
            
        }else {
            
            JOptionPane.showMessageDialog(null,"Ya has gastado todos los puntos de habilidad");
            jRadioButtonArmFug.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonArmFugActionPerformed

    private void jButtonAddFueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddFueActionPerformed
        // TODO add your handling code here:
        
       int num = Integer.parseInt(jButtonAddFue.getText());
       
       if (num == 40 ){
           
           jButtonAddFue.setEnabled(false);
           jLabelFue.setText("90");
           
           jButtonAddDes.setText("30");
           jButtonAddCon.setText("30");
           jButtonAddTam.setText("30");
           jButtonAddInt.setText("30");
           jButtonAddEdu.setText("30");
           
       }else if (num == 30 && cont30 < 2){
           
           jButtonAddFue.setEnabled(false);
           jLabelFue.setText("80");
           
           cont30 = cont30+1;
           
           if(cont30 == 2){
               
           jButtonAddDes.setText("20");
           jButtonAddCon.setText("20");
           jButtonAddTam.setText("20");
           jButtonAddInt.setText("20");
           jButtonAddEdu.setText("20"); 
               
           }
     
       }else if (num == 20 && cont20 < 2){
           
           jButtonAddFue.setEnabled(false);
           jLabelFue.setText("70");
           
           cont20 = cont20+1;
           
           if(cont20 == 2){     
               
           jButtonAddDes.setEnabled(false);
           jButtonAddCon.setEnabled(false);
           jButtonAddTam.setEnabled(false);
           jButtonAddInt.setEnabled(false);
           jButtonAddEdu.setEnabled(false);
           
           cort = cort +1;
               
           }
           
       }
        
    }//GEN-LAST:event_jButtonAddFueActionPerformed

    private void jButtonAddConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddConActionPerformed
        // TODO add your handling code here:
        int num = Integer.parseInt(jButtonAddCon.getText());
       
       if (num == 40 ){
           
           jButtonAddCon.setEnabled(false);
           jLabelCon.setText("90");
           
           jButtonAddDes.setText("30");
           jButtonAddFue.setText("30");
           jButtonAddTam.setText("30");
           jButtonAddInt.setText("30");
           jButtonAddEdu.setText("30");
           
       }else if (num == 30 && cont30 < 2){
           
           jButtonAddCon.setEnabled(false);
           jLabelCon.setText("80");
           
           cont30 = cont30+1;
           
           if(cont30 == 2){
               
           jButtonAddDes.setText("20");
           jButtonAddFue.setText("20");
           jButtonAddTam.setText("20");
           jButtonAddInt.setText("20");
           jButtonAddEdu.setText("20"); 
               
           }
     
       }else if (num == 20 && cont20 < 2){
           
           jButtonAddCon.setEnabled(false);
           jLabelCon.setText("70");
           
           cont20 = cont20+1;
           
           if(cont20 == 2){     
               
           jButtonAddDes.setEnabled(false);
           jButtonAddFue.setEnabled(false);
           jButtonAddTam.setEnabled(false);
           jButtonAddInt.setEnabled(false);
           jButtonAddEdu.setEnabled(false);
           
           cort = cort +1;
               
           }
           
       }
        
    }//GEN-LAST:event_jButtonAddConActionPerformed

    private void jButtonAddTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTamActionPerformed
        // TODO add your handling code here:
        int num = Integer.parseInt(jButtonAddTam.getText());
       
       if (num == 40 ){
           
           jButtonAddTam.setEnabled(false);
           jLabelTam.setText("90");
           
           jButtonAddDes.setText("30");
           jButtonAddCon.setText("30");
           jButtonAddFue.setText("30");
           jButtonAddInt.setText("30");
           jButtonAddEdu.setText("30");
           
       }else if (num == 30 && cont30 < 2){
           
           jButtonAddTam.setEnabled(false);
           jLabelTam.setText("80");
           
           cont30 = cont30+1;
           
           if(cont30 == 2){
               
           jButtonAddDes.setText("20");
           jButtonAddCon.setText("20");
           jButtonAddFue.setText("20");
           jButtonAddInt.setText("20");
           jButtonAddEdu.setText("20"); 
               
           }
     
       }else if (num == 20 && cont20 < 2){
           
           jButtonAddTam.setEnabled(false);
           jLabelTam.setText("70");
           
           cont20 = cont20+1;
           
           if(cont20 == 2){      
               
           jButtonAddDes.setEnabled(false);
           jButtonAddCon.setEnabled(false);
           jButtonAddFue.setEnabled(false);
           jButtonAddInt.setEnabled(false);
           jButtonAddEdu.setEnabled(false);
           
           cort = cort +1;
           
               
           }
           
       }
    }//GEN-LAST:event_jButtonAddTamActionPerformed

    private void jButtonAddIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddIntActionPerformed
        // TODO add your handling code here:
        int num = Integer.parseInt(jButtonAddInt.getText());
       
       if (num == 40 ){
           
           jButtonAddInt.setEnabled(false);
           jLabelInt.setText("90");
           
           jButtonAddDes.setText("30");
           jButtonAddCon.setText("30");
           jButtonAddTam.setText("30");
           jButtonAddFue.setText("30");
           jButtonAddEdu.setText("30");
           
       }else if (num == 30 && cont30 < 2){
           
           jButtonAddInt.setEnabled(false);
           jLabelInt.setText("80");
           
           cont30 = cont30+1;
           
           if(cont30 == 2){
               
           jButtonAddDes.setText("20");
           jButtonAddCon.setText("20");
           jButtonAddTam.setText("20");
           jButtonAddFue.setText("20");
           jButtonAddEdu.setText("20"); 
               
           }
     
       }else if (num == 20 && cont20 < 2){
           
           jButtonAddInt.setEnabled(false);
           jLabelInt.setText("70");
           
           cont20 = cont20+1;
           
           if(cont20 == 2){      
               
           jButtonAddDes.setEnabled(false);
           jButtonAddCon.setEnabled(false);
           jButtonAddTam.setEnabled(false);
           jButtonAddFue.setEnabled(false);
           jButtonAddEdu.setEnabled(false);
           
           cort = cort +1;
               
           }
           
       }
    }//GEN-LAST:event_jButtonAddIntActionPerformed

    private void jButtonAddEduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddEduActionPerformed
        // TODO add your handling code here:
        int num = Integer.parseInt(jButtonAddEdu.getText());
       
       if (num == 40 ){
           
           jButtonAddEdu.setEnabled(false);
           jLabelEdu.setText("90");
           
           jButtonAddDes.setText("30");
           jButtonAddCon.setText("30");
           jButtonAddTam.setText("30");
           jButtonAddInt.setText("30");
           jButtonAddFue.setText("30");
           
       }else if (num == 30 && cont30 < 2){
           
           jButtonAddEdu.setEnabled(false);
           jLabelEdu.setText("80");
           
           cont30 = cont30+1;
           
           if(cont30 == 2){
               
           jButtonAddDes.setText("20");
           jButtonAddCon.setText("20");
           jButtonAddTam.setText("20");
           jButtonAddInt.setText("20");
           jButtonAddFue.setText("20"); 
               
           }
     
       }else if (num == 20 && cont20 < 2){
           
           jButtonAddEdu.setEnabled(false);
           jLabelEdu.setText("70");
           
           cont20 = cont20+1;
           
           if(cont20 == 2){  
           
            jButtonAddInt.setEnabled(false);    
            jButtonAddDes.setEnabled(false);
            jButtonAddCon.setEnabled(false);
            jButtonAddTam.setEnabled(false);
            jButtonAddFue.setEnabled(false);
            
            cort = cort +1;
               
           }
           
       }
    }//GEN-LAST:event_jButtonAddEduActionPerformed

    private void jButtonAddDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddDesActionPerformed
        // TODO add your handling code here:
        int num = Integer.parseInt(jButtonAddDes.getText());
       
       if (num == 40 ){
           
           jButtonAddDes.setEnabled(false);
           jLabelDes.setText("90");
           
           jButtonAddFue.setText("30");
           jButtonAddCon.setText("30");
           jButtonAddTam.setText("30");
           jButtonAddInt.setText("30");
           jButtonAddEdu.setText("30");
           
       }else if (num == 30 && cont30 < 2){
           
           jButtonAddDes.setEnabled(false);
           jLabelDes.setText("80");
           
           cont30 = cont30+1;
           
           if(cont30 == 2){
               
           jButtonAddFue.setText("20");
           jButtonAddCon.setText("20");
           jButtonAddTam.setText("20");
           jButtonAddInt.setText("20");
           jButtonAddEdu.setText("20"); 
               
           }
     
       }else if (num == 20 && cont20 < 2){
           
           jButtonAddDes.setEnabled(false);
           jLabelDes.setText("70");
           
           cont20 = cont20+1;
           
           if(cont20 == 2){  
           
           jButtonAddFue.setEnabled(false);
           jButtonAddCon.setEnabled(false);
           jButtonAddTam.setEnabled(false);
           jButtonAddInt.setEnabled(false);
           jButtonAddEdu.setEnabled(false);
           
           cort = cort +1;
               
           }
           
       }
    }//GEN-LAST:event_jButtonAddDesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
           jButtonAddFue.setEnabled(true);
           jButtonAddCon.setEnabled(true);
           jButtonAddTam.setEnabled(true);
           jButtonAddInt.setEnabled(true);
           jButtonAddEdu.setEnabled(true);
           jButtonAddDes.setEnabled(true);
           
           jButtonAddFue.setText("40");
           jButtonAddCon.setText("40");
           jButtonAddTam.setText("40");
           jButtonAddInt.setText("40");
           jButtonAddEdu.setText("40"); 
           jButtonAddDes.setText("40");
           
           jLabelFue.setText("50");
           jLabelCon.setText("50");
           jLabelTam.setText("50");
           jLabelInt.setText("50");
           jLabelEdu.setText("50");
           jLabelDes.setText("50");
           
           cont20 = 0;
           cont30 = 0;
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creacion_Personaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creacion_Personaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creacion_Personaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creacion_Personaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Creacion_Personaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAcep;
    private javax.swing.JButton jButtonAddCon;
    private javax.swing.JButton jButtonAddDes;
    private javax.swing.JButton jButtonAddEdu;
    private javax.swing.JButton jButtonAddFue;
    private javax.swing.JButton jButtonAddInt;
    private javax.swing.JButton jButtonAddTam;
    private javax.swing.JButton jButtonAnt;
    private javax.swing.JButton jButtonArmFug;
    private javax.swing.JButton jButtonBio;
    private javax.swing.JButton jButtonBuscLib;
    private javax.swing.JButton jButtonCerr;
    private javax.swing.JButton jButtonCienOcu;
    private javax.swing.JButton jButtonCon;
    private javax.swing.JButton jButtonDes;
    private javax.swing.JButton jButtonDesc;
    private javax.swing.JButton jButtonDis;
    private javax.swing.JButton jButtonEdu;
    private javax.swing.JButton jButtonEsc;
    private javax.swing.JButton jButtonEsq;
    private javax.swing.JButton jButtonFar;
    private javax.swing.JButton jButtonFra;
    private javax.swing.JButton jButtonFue;
    private javax.swing.JButton jButtonHis;
    private javax.swing.JButton jButtonInt;
    private javax.swing.JButton jButtonLat;
    private javax.swing.JButton jButtonMec;
    private javax.swing.JButton jButtonMed;
    private javax.swing.JButton jButtonOcu;
    private javax.swing.JButton jButtonPer;
    private javax.swing.JButton jButtonPsi;
    private javax.swing.JButton jButtonRus;
    private javax.swing.JButton jButtonSegRas;
    private javax.swing.JButton jButtonTam;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCon;
    private javax.swing.JLabel jLabelDes;
    private javax.swing.JLabel jLabelEdu;
    private javax.swing.JLabel jLabelFue;
    private javax.swing.JLabel jLabelHab;
    private javax.swing.JLabel jLabelInt;
    private javax.swing.JLabel jLabelTam;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelEst;
    private javax.swing.JRadioButton jRadioButtonAnt;
    private javax.swing.JRadioButton jRadioButtonArmFug;
    private javax.swing.JRadioButton jRadioButtonBio;
    private javax.swing.JRadioButton jRadioButtonBuscLib;
    private javax.swing.JRadioButton jRadioButtonCerr;
    private javax.swing.JRadioButton jRadioButtonCienOcu;
    private javax.swing.JRadioButton jRadioButtonDesc;
    private javax.swing.JRadioButton jRadioButtonDisc;
    private javax.swing.JRadioButton jRadioButtonEsc;
    private javax.swing.JRadioButton jRadioButtonEsq;
    private javax.swing.JRadioButton jRadioButtonFarm;
    private javax.swing.JRadioButton jRadioButtonFran;
    private javax.swing.JRadioButton jRadioButtonHist;
    private javax.swing.JRadioButton jRadioButtonLat;
    private javax.swing.JRadioButton jRadioButtonMec;
    private javax.swing.JRadioButton jRadioButtonMed;
    private javax.swing.JRadioButton jRadioButtonOcu;
    private javax.swing.JRadioButton jRadioButtonPers;
    private javax.swing.JRadioButton jRadioButtonPsi;
    private javax.swing.JRadioButton jRadioButtonRus;
    private javax.swing.JRadioButton jRadioButtonSegRas;
    private javax.swing.JTextField jTextFieldApe;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldProf;
    // End of variables declaration//GEN-END:variables

}
